### ISSUE TITLE
can not read dataset

### ISSUE THREAD

**Issue by finger-monkey** [CEA-LIST/adv-reid#1]
![image](https://user-images.githubusercontent.com/52326609/112585169-3f842300-8e34-11eb-8122-cf7ec91a496c.png)
could you tell me how to solve this problem?
The following is the order I executed:
python train.py \
        ‘/data/GYP/code/CVPRW20_adv-reid/output’ \
        ‘../../data/market1501/’ \
        --dataset 'market' \
        --gpu 1\
        --lr 0.0003 \
        -wd 0 \
        -n 100 \
        -f checkpoint_default.py\
        -b 72 \
        -ni 4 \
        -e 2048 \
        --pretrained \
        --triplet \
        --soft \
        --id_batch 
I print the value:
![image](https://user-images.githubusercontent.com/52326609/112585462-ce913b00-8e34-11eb-8a61-a9b097df38ae.png)
shows that:
![image](https://user-images.githubusercontent.com/52326609/112585495-dea91a80-8e34-11eb-8400-7a9ef5da9509.png)
so I think the the program did not read the dataset properly

**Comment by qbouniot** [comment]
Hi ! Have you run the script `sort_dataset.py` ? You have to add the path to your dataset in the script before running it. The script will sort the images in the right folders for the dataloaders.
I forgot to mention it in the readme, thank you for pointing this out !

**Comment by finger-monkey** [comment]
thank you! I will try again.

**Comment by finger-monkey** [comment]
I operated according to your suggestion, but the same problem still appeared.

python train.py \
        ‘/data/GYP/code/CVPRW20_adv-reid/output’ \
        ‘../../data/market1501/sorted/’ \
        --dataset 'market' \
        --gpu 1\
        --lr 0.0003 \
        -wd 0 \
        -n 100 \
        -f checkpoint_default.py\
        -b 72 \
        -ni 4 \
        -e 2048 \
        --pretrained \
        --triplet \
        --soft \
        --id_batch

**Comment by qbouniot** [comment]
Can you confirm that your dataset folder (../../data/market1501/) has the folders: 'bounding_box_train', 'bounding_box_test' and 'query' ? 
These 3 folders should contain the training, gallery and query images respectively and the dataset_folder argument should be the folder containing them.

**Comment by finger-monkey** [comment]
> Can you confirm that your dataset folder (../../data/market1501/) has the folders: 'bounding_box_train', 'bounding_box_test' and 'query' ?
> These 3 folders should contain the training, gallery and query images respectively and the dataset_folder argument should be the folder containing them.
Thank you for your reply. I've already tried.But the same problem still arose
![image](https://user-images.githubusercontent.com/52326609/113501057-4c4ff780-9555-11eb-802d-1345e44bea24.png)
![image](https://user-images.githubusercontent.com/52326609/113501117-ab157100-9555-11eb-8cef-2d6143dd326f.png)

python train.py \
        ‘/data/GYP/code/CVPRW20_adv-reid/output’ \
        ‘../../data/market1501/sorted’ \
        --dataset 'market' \
        --gpu 1\
        --lr 0.0003 \
        -wd 0 \
        -n 100 \
        -f checkpoint_default.py\
        -b 72 \
        -ni 4 \
        -e 2048 \
        --pretrained \
        --triplet \
        --soft \
        --id_batch

**Comment by finger-monkey** [comment]
In fact, I want to do some experiments on defense. Could you give me some help?
![image](https://user-images.githubusercontent.com/52326609/113501492-08aabd00-9558-11eb-95cc-1450775a279f.png)
 If possible, I hope to get adversarial examples of the query of the three methods in your paper.
![image](https://user-images.githubusercontent.com/52326609/113501301-a00f1080-9556-11eb-9adf-6b159cf3479d.png)

**Comment by qbouniot** [comment]
From what I can see, since your glob.glob(probe) and glob.glob(train) are empty lists, the script cannot find the images. So I think you should check the paths of your images and verify if the paths ```os.path.join(self.probe_dir, '*.jpg')``` that we use are really the paths of your images. Maybe instead of using ```../../data/market1501/sorted``` as your ```dataset_folder``` argument, you could try to put the full path ```/data/GYP/data/market1501/sorted``` or ```/data/GYP/data/market1501```.

To evaluate with the methods described in our paper you can use the script ```gen_adv.py``` as described in the Readme, in section *Evaluating*. You can change the attack using the argument ```--attack``` (or ```-a```):  
 - ```-a IFGSM``` for SG. IFGSM
 - ```-a SMA``` for SMA
 - ```-a FNA``` for FNA

**Comment by finger-monkey** [comment]
thank you!
