### ISSUE TITLE
About the Paper

### ISSUE THREAD

**Issue by finger-monkey** [CEA-LIST/adv-reid#3]
![image](https://user-images.githubusercontent.com/52326609/116489290-3c62d380-a8c7-11eb-90d5-23236e662f4d.png)
![image](https://user-images.githubusercontent.com/52326609/116489343-54d2ee00-a8c7-11eb-879e-a728227d2ac9.png)

I have a confusion about the Equation, is the minus sign here a clericcal error? According your illustration,it seems that the sign should be a plus.
All the best.

**Comment by finger-monkey** [comment]
could you help me?

**Comment by qbouniot** [comment]
The minus sign is not an error. The direction of the movement in the feature space is given by the gradient of the distance between the features and the guides. A positive gradient will **push away** the features, so we use a positive gradient for **pushing guides** (red arrows). A negative gradient will a **pull** the features towards the guide, so we use a negative gradient for **pulling guides** (blue arrows).
If you want more details, you can check my blog post on the paper : https://qbouniot.github.io/article/2020/05/06/adv_reid.html

**Comment by finger-monkey** [comment]
thanks,again.
