### ISSUE TITLE
the offline adversarial training defense

### ISSUE THREAD

**Issue by shgal637** [CEA-LIST/adv-reid#5]
I have a problem to training a Classification model using  the offline adversarial training defense method. I don't know what command to use.
Hope you can help me.
Thanks and Regards.

**Comment by qbouniot** [comment]
Hi, thank you for your interest on our work !
To run an offline adversarial training, please refer to the paper from Bai et al.: "Adversarial Metric Attack for Person Re-identification". It describes the process of the training in Section 4.
In short, you have to generate an adversarial version of your dataset and save the images. Then you merge the adversarial images saved with the original images. Finally, you train on the merged dataset.

**Comment by shgal637** [comment]
Thank you!
